#!/bin/sh

export PATH=/bin

echo ""
echo "===== Linux 2.6.11.12 + BusyBox 1.00 ====="
echo ""

mount -t proc none /proc
mount -t sysfs none /sys

echo "Welcome to BusyBox shell!"
echo ""

exec /bin/sh
